### ISSUE TITLE
Help with configuration

### ISSUE THREAD

**Issue by ojnde** [forelleblau/ioBroker.gsmsms#19]
Any idea what's going on here? Using minicom everything works fine without additional settings. Checked modem parameters set on modem as well.

2024-10-17 19:28:31.180 - info: host.statistic "system.adapter.gsmsms.0" enabled
2024-10-17 19:28:31.455 - info: host.statistic instance system.adapter.gsmsms.0 in version "0.0.6" started with pid 1955
2024-10-17 19:28:32.006 - debug: gsmsms.0 (1955) Redis Objects: Use Redis connection: 127.0.0.1:9001
2024-10-17 19:28:32.027 - debug: gsmsms.0 (1955) Objects client ready ... initialize now
2024-10-17 19:28:32.028 - debug: gsmsms.0 (1955) Objects create System PubSub Client
2024-10-17 19:28:32.028 - debug: gsmsms.0 (1955) Objects create User PubSub Client
2024-10-17 19:28:32.064 - debug: gsmsms.0 (1955) Objects client initialize lua scripts
2024-10-17 19:28:32.068 - debug: gsmsms.0 (1955) Objects connected to redis: 127.0.0.1:9001
2024-10-17 19:28:32.090 - debug: gsmsms.0 (1955) Redis States: Use Redis connection: 127.0.0.1:9000
2024-10-17 19:28:32.144 - debug: gsmsms.0 (1955) States create System PubSub Client
2024-10-17 19:28:32.144 - debug: gsmsms.0 (1955) States create User PubSub Client
2024-10-17 19:28:32.208 - debug: gsmsms.0 (1955) States connected to redis: 127.0.0.1:9000
2024-10-17 19:28:32.360 - info: gsmsms.0 (1955) starting. Version 0.0.6 in /opt/iobroker/node_modules/iobroker.gsmsms, node: v20.18.0, js-controller: 6.0.11
2024-10-17 19:28:32.368 - debug: gsmsms.0 (1955) port/dev/ttyUSB4
2024-10-17 19:28:32.369 - debug: gsmsms.0 (1955) autoDeleteOnReceive: false
2024-10-17 19:28:32.369 - debug: gsmsms.0 (1955) enableConcatenation: true
2024-10-17 19:28:32.369 - debug: gsmsms.0 (1955) incomingCallIndication: false
2024-10-17 19:28:32.369 - debug: gsmsms.0 (1955) incomingSMSIndication: true
2024-10-17 19:28:32.369 - debug: gsmsms.0 (1955) pin:
2024-10-17 19:28:32.369 - debug: gsmsms.0 (1955) customInitCommand: AT+CMGF=1
2024-10-17 19:28:32.369 - debug: gsmsms.0 (1955) cnmiModemOpen: AT+CNMI=2,1,0,2,0
2024-10-17 19:28:32.369 - debug: gsmsms.0 (1955) cnmiModemClosed: AT+CNMI=2,0,2,2,1
2024-10-17 19:28:32.370 - debug: gsmsms.0 (1955) getSignalQuality: true
2024-10-17 19:28:32.370 - debug: gsmsms.0 (1955) pollinginterval: 30000
2024-10-17 19:28:32.370 - debug: gsmsms.0 (1955) baudRate: 115200
2024-10-17 19:28:32.370 - debug: gsmsms.0 (1955) dataBits: 8
2024-10-17 19:28:32.370 - debug: gsmsms.0 (1955) stopBits: 1
2024-10-17 19:28:32.370 - debug: gsmsms.0 (1955) parity: none
2024-10-17 19:28:32.370 - debug: gsmsms.0 (1955) rtscts: false
2024-10-17 19:28:32.370 - debug: gsmsms.0 (1955) xon: false
2024-10-17 19:28:32.370 - debug: gsmsms.0 (1955) xoff: false
2024-10-17 19:28:32.370 - debug: gsmsms.0 (1955) xany: false
2024-10-17 19:28:35.341 - debug: gsmsms.0 (1955) GSM-Modem successfully opened
2024-10-17 19:28:35.342 - debug: gsmsms.0 (1955) Modem msg: {"status":"success","request":"connectModem","data":{"modem":"/dev/ttyUSB4","status":"Online"}}
2024-10-17 19:28:35.342 - info: gsmsms.0 (1955) Modem opened successfully, Port: "/dev/ttyUSB4" Status: "Online"
2024-10-17 19:28:35.344 - debug: gsmsms.0 (1955) Modem Write: ATZ
2024-10-17 19:28:35.381 - info: host.statistic instance system.adapter.gsmsms.0 terminated by request of the instance itself and will not be restarted, before user restarts it.
2024-10-17 19:28:35.381 - info: host.statistic Do not restart adapter system.adapter.gsmsms.0 because desired by instance
2024-10-17 19:28:55.288 - info: digitalstrom.0 (1105) State value to set for "digitalstrom.0.apartment.sensors.outdoor.sunazimuth" has to be type "number" but received type "string"
2024-10-17 19:28:55.350 - info: digitalstrom.0 (1105) State value to set for "digitalstrom.0.apartment.sensors.outdoor.sunelevation" has to be type "number" but received type "string"
2024-10-17 19:29:05.345 - warn: gsmsms.0 (1955) Error initializing GSM-modem - Error: timeout:
{"_events":{},"_eventsCount":1,"_maxListeners":100,"command":"ATZ","add_time":"2024-10-17T17:28:35.342Z","id":2,"timeout":30000,"inProgress":true,"execute_time":"2024-10-17T17:28:35.344Z"}

**Comment by ojnde** [comment]
This problem was caused by iobroker - although being in group dialout - still needed administrator privileges to access ttyUSBx. Solved by uninstalling **modemmanager** following a hint from another forum. Connection works now, but:

2024-10-19 11:14:48.963 - debug: gsmsms.0 (3586) Call callback for: AT+CPMS="SM"
--
2024-10-19 11:14:48.963 - debug: gsmsms.0 (3586) Modem Received:
2024-10-19 11:14:48.963 - debug: gsmsms.0 (3586) Modem Received: OK
2024-10-19 11:14:48.963 - debug: gsmsms.0 (3586) Sim Memory Result: {"status":"success","request":"checkSimMemory","data":{"used":5,"total":20}}
2024-10-19 11:14:48.964 - debug: gsmsms.0 (3586) Modem Write: AT+CMGL="ALL"
2024-10-19 11:14:49.000 - debug: gsmsms.0 (3586) state gsmsms.0.admin.ownNumber changed: +4915158728967 (ack = true)
2024-10-19 11:14:49.001 - debug: gsmsms.0 (3586) state gsmsms.0.admin.ownName changed: Eigene Rufnummer (ack = true)
2024-10-19 11:14:49.036 - debug: gsmsms.0 (3586) Modem Received: AT+CMGL="ALL"
2024-10-19 11:14:49.036 - debug: gsmsms.0 (3586) Activate Message Processing for: AT+CMGL="ALL"
2024-10-19 11:14:49.036 - debug: gsmsms.0 (3586) Modem Received:
2024-10-19 11:14:49.036 - debug: gsmsms.0 (3586) Modem Received: +CMGL: 0,"REC READ","72170","","24/10/16,19:24:39+08"
2024-10-19 11:14:49.037 - debug: gsmsms.0 (3586) Modem Received: 003200360032003000310031003500300035003200347111003800330033002D007200630073006300660067
2024-10-19 11:14:49.047 - error: gsmsms.0 (3586) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-10-19 11:14:49.047 - error: gsmsms.0 (3586) unhandled promise rejection: [sprintf] expecting number but found undefined "undefined"
2024-10-19 11:14:49.048 - error: gsmsms.0 (3586) Error: [sprintf] expecting number but found undefined "undefined"
at str_format.format (/opt/iobroker/node_modules/sprintf/lib/sprintf.js:163:12)
at str_format (/opt/iobroker/node_modules/sprintf/lib/sprintf.js:77:28)
at SCTS.parse (/opt/iobroker/node_modules/node-pdu/PDU/SCTS.js:53:18)
at Helper.initVars (/opt/iobroker/node_modules/node-pdu/PDU/Helper.js:299:31)
at PDU.parse (/opt/iobroker/node_modules/node-pdu/pdu.js:128:19)
at item.logic (/opt/iobroker/node_modules/serialport-gsm/lib/functions/modem.js:1463:30)
at /opt/iobroker/node_modules/serialport-gsm/lib/functions/modem.js:1205:50
at Array.forEach ()
at /opt/iobroker/node_modules/serialport-gsm/lib/functions/modem.js:1104:16
at Array.forEach ()
2024-10-19 11:14:49.048 - error: gsmsms.0 (3586) [sprintf] expecting number but found undefined "undefined"
2024-10-19 11:14:49.049 - debug: gsmsms.0 (3586) Setze CNMI auf Speichern
2024-10-19 11:14:49.550 - info: gsmsms.0 (3586) terminating
2024-10-19 11:14:49.550 - warn: gsmsms.0 (3586) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-10-19 11:14:50.088 - error: host.statistic instance system.adapter.gsmsms.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-10-19 11:14:50.089 - info: host.statistic Restart adapter system.adapter.gsmsms.0 because enabled

**Comment by ojnde** [comment]
Setting mode to PDU finally made it working.
